image: bradrydzewski/go:1.3
script:
    - sudo apt-get update -qq
    - sudo apt-get -y install bzr mercurial python-pip
    - sudo apt-get -y install automake build-essential git gobject-introspection libglib2.0-dev libjpeg-turbo8-dev libpng12-dev gtk-doc-tools
    - go get
    - go get -t
    - go build
    - go test -gocheck.v
    - go test -gocheck.v -gocheck.b -coverprofile=coverage.txt -covermode=count
    - cd fetch && go test -v -coverprofile=coverage.txt -covermode=count
    - cat fetch/coverage.txt >> coverage.txt
    - sudo pip install codecov
    - codecov --token=$$codecovToken
notify:
    webhook:
        urls:
            - https://dronebot.vokal.io/hook
        on_success: true
        on_failure: true
